
server:
  port: 8080

spring:
  application:
    name: coinkeeper

  datasource:
    url: jdbc:postgresql://localhost/coin-keeper
    username: ${LOGIN_BD}
    password: ${PASS_BD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
    show-sql: true