create table public.currency
(
    currency_id          bigint generated by default as identity
        primary key,
    currency_name        varchar(255)
);

create table public.users
(
    user_id     bigint generated by default as identity
        primary key,
    account     bigint,
    currency_id bigint
        constraint currency_fkey
            references public.currency,
    email       varchar(255)
        unique,
    password    varchar(255)
);

create table public.finance
(
    name        varchar(255),
    added_at    timestamp(6) with time zone,
    finance_id bigint generated by default as identity
        primary key,
    price       bigint,
    user_id     bigint
        constraint user_id_fkey_finance
            references public.users,
    finance_type varchar(10),
    category     varchar(255)
);


