create table public.currency
(
    currency_id          bigint generated by default as identity
        primary key,
    currency_name        varchar(255)
);

create table public.users
(
    user_id     bigint generated by default as identity
        primary key,
    account     bigint,
    currency_id bigint
        constraint fk_currency_user_currency_id
            references public.currency
            ON UPDATE CASCADE
            ON DELETE CASCADE,

    email       varchar(255)
        unique,
    password    varchar(255)
);

create table public.finance
(
    name        varchar(255),
    added_at    timestamp(6) with time zone,
    finance_id bigint generated by default as identity
        primary key,
    price       bigint,
    user_id     bigint
        constraint fk_user_finance_user_id
            references public.users ("user_id"),
    finance_type varchar(10),
    category     varchar(255)
);

create table public.authority
(
    authority_id bigint generated by default as identity
        primary key,
    authority_name varchar(10) not null unique
);

create table public.user_authority
(
    id bigint generated by default as identity
        primary key,
    user_id bigint not null
        constraint fk_user_authority_user_id
            references public.users ("user_id")
            ON UPDATE CASCADE
            ON DELETE CASCADE,
    authority_id bigint not null
        constraint fk_user_authority_authority_id
            references public.authority ("authority_id")
            ON UPDATE CASCADE
            ON DELETE CASCADE
);
